services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=docker-user
      - RABBITMQ_DEFAULT_PASS=docker-password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  db-pg:
    container_name: db-pg
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker-user
      - POSTGRES_PASSWORD=docker-password
      - POSTGRES_DB=orders

  roboshop-orders-api:
    container_name: roboshop-orders-api
    build:
      context: .
    ports:
      - 3333:3333
    depends_on:
      - db-pg
      - rabbitmq
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - PORT=3333

volumes:
  rabbitmq_data:
